# Partially Generated by Gemini 2.0 Flash
# -- Inital Form layout/alignment and controls
# -- Event handlers for clearing and restoring default text in the textbox

# TODO: add script input parameters for use in automation and scripting scenarios.
# TODO: general cleanup and refactoring of the code to improve readability and maintainability.
# TODO: improve UI/UX; will looking UI similar to https://github.com/christitustech/winutil

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

# Function to generate a random string
function New-RandomString {
    param(
        [int]$Length = 12
    )
    #Characters to use for generating the random string
    # TODO: Allow selection of allowed characters and symbols for random string generation.
    # TODO: Find a better way to set allowed characters for random string generation
    $characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+=-`~[]\{}|;':"",./<>?"
    $randomString = ""
    for ($i = 0; $i -lt $Length; $i++) {
        $randomIndex = Get-Random -Minimum 0 -Maximum ($characters.Length - 1)
        $randomString += $characters[$randomIndex]
    }
    return $randomString
}

# Create the form
$form = New-Object System.Windows.Forms.Form
$form.Text = "Random String Generator"
$form.Size = New-Object System.Drawing.Size(500, 380) # increased height
$form.StartPosition = "CenterScreen"
$form.AutoSize = $true

# Create the label for the number input
$numberLabel = New-Object System.Windows.Forms.Label
$numberLabel.Location = New-Object System.Drawing.Point(10, 20)
$numberLabel.Size = New-Object System.Drawing.Size(80, 20)
$numberLabel.Text = "String Length:"
$form.Controls.Add($numberLabel)

# Create the textbox for the number input
$numberTextBox = New-Object System.Windows.Forms.TextBox
$numberTextBox.Location = New-Object System.Drawing.Point(100, 20)
$numberTextBox.Size = New-Object System.Drawing.Size(90, 20)
$numberTextBox.Text = "8" # Set default text to 8
$numberTextBox.MaxLength = 4 # limit digits
$form.Controls.Add($numberTextBox)

# Add event handler for click to clear default text
$numberTextBox.Add_Enter({
    if ($this.Text -eq "8") {
        $this.Text = ""
    }
})

# Add event handler for leave to restore default text if empty
$numberTextBox.Add_Leave({
    if ([string]::IsNullOrEmpty($this.Text)) {
        $this.Text = "8"
    }
})

# Create the dropdown menu (ComboBox)
$lengthComboBox = New-Object System.Windows.Forms.ComboBox
$lengthComboBox.Location = New-Object System.Drawing.Point(195, 20)
$lengthComboBox.Size = New-Object System.Drawing.Size(40, 20)
$lengthComboBox.Items.AddRange(@("8", "16", "24", "32", "48", "64", "96", "128", "256", "384", "512", "768", "1024"))
$lengthComboBox.SelectedItem = "8"
$lengthComboBox.DropDownStyle = [System.Windows.Forms.ComboBoxStyle]::DropDownList
$form.Controls.Add($lengthComboBox)

# Create the label for displaying the string length variable
$lengthVariableLabel = New-Object System.Windows.Forms.Label
$lengthVariableLabel.Location = New-Object System.Drawing.Point(300, 20)
$lengthVariableLabel.Size = New-Object System.Drawing.Size(190, 20)
$lengthVariableLabel.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($lengthVariableLabel)

# Create the button to generate the string
$generateButton = New-Object System.Windows.Forms.Button
$generateButton.Location = New-Object System.Drawing.Point(10, 50)
$generateButton.Size = New-Object System.Drawing.Size(120, 30)
$generateButton.Text = "Generate String"
$form.Controls.Add($generateButton)

# Copy to clipboard
$copyButton = New-Object System.Windows.Forms.Button
$copyButton.Location = New-Object System.Drawing.Point(140, 50)
$copyButton.Size = New-Object System.Drawing.Size(120, 30)
$copyButton.Text = "Copy to Clipboard"
$copyButton.Add_Click({[System.Windows.Forms.Clipboard]::SetText($resultLabel.Text)})
$form.Controls.Add($copyButton)

# Create the label to display the generated string
$resultLabel = New-Object System.Windows.Forms.RichTextBox
$resultLabel.Location = New-Object System.Drawing.Point(10, 100)
$resultLabel.Size = New-Object System.Drawing.Size(400, 80)
$resultLabel.Text = ""
$resultLabel.WordWrap = $true
$resultLabel.ScrollBars = [System.Windows.Forms.RichTextBoxScrollBars]::Vertical
$resultLabel.ReadOnly = $true
$form.Controls.Add($resultLabel)

# Create labels for the last 5 outputs
$lastOutputsLabel = New-Object System.Windows.Forms.Label
$lastOutputsLabel.Location = New-Object System.Drawing.Point(40, 190)
$lastOutputsLabel.Size = New-Object System.Drawing.Size(360, 20)
$lastOutputsLabel.Text = "Last 5 Outputs:"
$form.Controls.Add($lastOutputsLabel)

$lastOutput1 = New-Object System.Windows.Forms.Label
$lastOutput1.Location = New-Object System.Drawing.Point(40, 210)
$lastOutput1.Size = New-Object System.Drawing.Size(300, 20)
$lastOutput1.Text = ""
$form.Controls.Add($lastOutput1)

$lastOutput2 = New-Object System.Windows.Forms.Label
$lastOutput2.Location = New-Object System.Drawing.Point(40, 230)
$lastOutput2.Size = New-Object System.Drawing.Size(300, 20)
$lastOutput2.Text = ""
$form.Controls.Add($lastOutput2)

$lastOutput3 = New-Object System.Windows.Forms.Label
$lastOutput3.Location = New-Object System.Drawing.Point(40, 250)
$lastOutput3.Size = New-Object System.Drawing.Size(300, 20)
$lastOutput3.Text = ""
$form.Controls.Add($lastOutput3)

$lastOutput4 = New-Object System.Windows.Forms.Label
$lastOutput4.Location = New-Object System.Drawing.Point(40, 270)
$lastOutput4.Size = New-Object System.Drawing.Size(300, 20)
$lastOutput4.Text = ""
$form.Controls.Add($lastOutput4)

$lastOutput5 = New-Object System.Windows.Forms.Label
$lastOutput5.Location = New-Object System.Drawing.Point(40, 290)
$lastOutput5.Size = New-Object System.Drawing.Size(300, 20)
$lastOutput5.Text = ""
$form.Controls.Add($lastOutput5)

# Create the label for displaying the string length variable
$HistorylengthLabel1 = New-Object System.Windows.Forms.Label
$HistorylengthLabel1.Location = New-Object System.Drawing.Point(10, 210)
$HistorylengthLabel1.Size = New-Object System.Drawing.Size(30, 20)
$HistorylengthLabel1.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($HistorylengthLabel1)

$HistorylengthLabel2 = New-Object System.Windows.Forms.Label
$HistorylengthLabel2.Location = New-Object System.Drawing.Point(10, 230)
$HistorylengthLabel2.Size = New-Object System.Drawing.Size(30, 20)
$HistorylengthLabel2.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($HistorylengthLabel2)

$HistorylengthLabel3 = New-Object System.Windows.Forms.Label
$HistorylengthLabel3.Location = New-Object System.Drawing.Point(10, 250)
$HistorylengthLabel3.Size = New-Object System.Drawing.Size(30, 20)
$HistorylengthLabel3.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($HistorylengthLabel3)

$HistorylengthLabel4 = New-Object System.Windows.Forms.Label
$HistorylengthLabel4.Location = New-Object System.Drawing.Point(10, 270)
$HistorylengthLabel4.Size = New-Object System.Drawing.Size(30, 20)
$HistorylengthLabel4.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($HistorylengthLabel4)

$HistorylengthLabel5 = New-Object System.Windows.Forms.Label
$HistorylengthLabel5.Location = New-Object System.Drawing.Point(10, 290)
$HistorylengthLabel5.Size = New-Object System.Drawing.Size(30, 20)
$HistorylengthLabel5.ForeColor = [System.Drawing.Color]::Red
$form.Controls.Add($HistorylengthLabel5)

# Array to store the last 5 outputs
$outputHistory = @("","","","","")

# Button click event handler
$generateButton.Add_Click({
    try {
        $length = [int]$lengthComboBox.SelectedItem # Default to dropdown value

        # Check if the textbox value is a valid integer and override
        if ($numberTextBox.Text -match '^\d+$') {
            $length = [int]$numberTextBox.Text
        } else {
            #If text box is not a number, and has text, do nothing.
            if ($numberTextBox.Text -ne ""){
                #Keep the textbox value as it is.
            }
            else {
                #Textbox is empty, set it to the combobox value.
                $numberTextBox.text = $lengthComboBox.SelectedItem
            }
        }

        $lengthVariableLabel.Text = "Length: " + $length

        # Validate $length before using it
        if (-not ($length -is [int]) -or $length -le 0) {
            $resultLabel.Text = "Please enter a valid positive integer for length."
            return
        }

        $randomString = New-RandomString -Length $length
        $resultLabel.Text = $randomString

        # Store the generated string in an array for history
        #copy to clipboard
        #[System.Windows.Forms.Clipboard]::SetText($randomString)

        # Update output history
        $outputHistory[4] = $outputHistory[3]
        $outputHistory[3] = $outputHistory[2]
        $outputHistory[2] = $outputHistory[1]
        $outputHistory[1] = $outputHistory[0]
        $outputHistory[0] = $randomString

        # Update history length labels
        $HistorylengthLabel1.Text = $outputHistory[0].Length
        $HistorylengthLabel2.Text = $outputHistory[1].Length
        $HistorylengthLabel3.Text = $outputHistory[2].Length
        $HistorylengthLabel4.Text = $outputHistory[3].Length
        $HistorylengthLabel5.Text = $outputHistory[4].Length

        # Display output history
        $output1 = "1. " + $outputHistory[0]
        $lastOutput1.Text = $output1.Substring(0, [Math]::Min(44, $output1.Length))
        $output2 = "2. " + $outputHistory[1]
        $lastOutput2.Text = $output2.Substring(0, [Math]::Min(44, $output2.Length))
        $output3 = "3. " + $outputHistory[2]
        $lastOutput3.Text = $output3.Substring(0, [Math]::Min(44, $output3.Length))
        $output4 = "4. " + $outputHistory[3]
        $lastOutput4.Text = $output4.Substring(0, [Math]::Min(44, $output4.Length))
        $output5 = "5. " + $outputHistory[4]
        $lastOutput5.Text = $output5.Substring(0, [Math]::Min(44, $output5.Length))

    } catch {
        $resultLabel.Text = "An error occurred."
    }
})

#combobox change event.
$lengthComboBox.Add_SelectedIndexChanged({
    $numberTextBox.Text = ""
})

# Copy buttons for history
$copyButton1 = New-Object System.Windows.Forms.Button
$copyButton1.Location = New-Object System.Drawing.Point(350, 210)
$copyButton1.Size = New-Object System.Drawing.Size(80, 20)
$copyButton1.Text = "Copy"
$copyButton1.Add_Click({[System.Windows.Forms.Clipboard]::SetText($outputHistory[0])})
$form.Controls.Add($copyButton1)

$copyButton2 = New-Object System.Windows.Forms.Button
$copyButton2.Location = New-Object System.Drawing.Point(350, 230)
$copyButton2.Size = New-Object System.Drawing.Size(80, 20)
$copyButton2.Text = "Copy"
$copyButton2.Add_Click({[System.Windows.Forms.Clipboard]::SetText($outputHistory[1])})
$form.Controls.Add($copyButton2)

$copyButton3 = New-Object System.Windows.Forms.Button
$copyButton3.Location = New-Object System.Drawing.Point(350, 250)
$copyButton3.Size = New-Object System.Drawing.Size(80, 20)
$copyButton3.Text = "Copy"
$copyButton3.Add_Click({[System.Windows.Forms.Clipboard]::SetText($outputHistory[2])})
$form.Controls.Add($copyButton3)

$copyButton4 = New-Object System.Windows.Forms.Button
$copyButton4.Location = New-Object System.Drawing.Point(350, 270)
$copyButton4.Size = New-Object System.Drawing.Size(80, 20)
$copyButton4.Text = "Copy"
$copyButton4.Add_Click({[System.Windows.Forms.Clipboard]::SetText($outputHistory[3])})
$form.Controls.Add($copyButton4)

$copyButton5 = New-Object System.Windows.Forms.Button
$copyButton5.Location = New-Object System.Drawing.Point(350, 290)
$copyButton5.Size = New-Object System.Drawing.Size(80, 20)
$copyButton5.Text = "Copy"
$copyButton5.Add_Click({[System.Windows.Forms.Clipboard]::SetText($outputHistory[4])})
$form.Controls.Add($copyButton5)

# Show the form
$form.Add_Shown({$form.Activate()})
[void]$form.ShowDialog()